# Generated by Django 4.2.6 on 2023-10-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_tage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tage',
            new_name='tag',
        ),
    ]
