# Generated by Django 4.2.6 on 2023-10-20 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Create at'),
        ),
    ]
