# Generated by Django 4.2.6 on 2024-02-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('sale', 'sale'), ('new', 'new'), ('feature', 'feature')], max_length=10, verbose_name='Flag'),
        ),
    ]
