# Generated by Django 4.2.6 on 2024-03-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_code_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(default='N0NELLHN', max_length=9),
        ),
    ]
