# Generated by Django 4.2.6 on 2024-03-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_code_phone_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(default='W7OO7DEQ', max_length=9),
        ),
    ]
