# Generated by Django 4.2.6 on 2024-03-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_phone_alter_profile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(default='BCZLZL0D', max_length=9),
        ),
    ]
