# Generated by Django 4.2.6 on 2024-03-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_phone_alter_profile_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(default='TEWN9OY4', max_length=9),
        ),
    ]
