<<<<<<< HEAD
# Generated by Django 4.2.6 on 2024-04-27 06:27
=======
# Generated by Django 4.2.6 on 2024-03-17 19:24
>>>>>>> 53ed92237f47e8e5b0f7bcac5a64314cbb01f508

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_phone_alter_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
<<<<<<< HEAD
            field=models.CharField(default='K5MHJ3KV', max_length=9),
=======
            field=models.CharField(default='973IZMF5', max_length=9),
>>>>>>> 53ed92237f47e8e5b0f7bcac5a64314cbb01f508
        ),
    ]
