# Generated by Django 4.2.6 on 2023-11-07 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_delivery_time_order_ime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ime',
            new_name='delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Completed', 'Completed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='JACKT9P9', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Recieved', 'Recieved'), ('Processed', 'Processed'), ('Shipped', 'Shipped')], default='Recieved', max_length=10),
        ),
    ]
