# Generated by Django 4.2.6 on 2024-03-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_code_alter_order_status'),
        ('orders', '0013_alter_cart_status_alter_order_code_and_more'),
    ]

    operations = [
    ]
