# Generated by Django 4.2.6 on 2024-04-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_code_alter_order_status'),
        ('orders', '0014_merge_20240317_2302'),
    ]

    operations = [
    ]
