# Generated by Django 4.2.6 on 2024-04-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_merge_20240427_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='A2JR9GFD', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Recieved', 'Recieved'), ('Delivered', 'Delivered')], default='Recieved', max_length=10),
        ),
    ]
