# Generated by Django 4.2.6 on 2024-04-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_code_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Completed', 'Completed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='AHTE72KP', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Recieved', 'Recieved'), ('Processed', 'Processed'), ('Shipped', 'Shipped')], default='Recieved', max_length=10),
        ),
    ]
